-- =====================================================
-- 01_roles_and_warehouse.sql
-- ロール階層（アクセスロール／ファンクショナルロール／WHロール）と
-- Sales_WH、Sales_RMの作成
-- 参照: ../構成.md #### Role, #### WH、RM
-- =====================================================

USE ROLE SECURITYADMIN;

-- ---------------------------------------------------
-- DATASOURCE DB 用ロール
-- ---------------------------------------------------
-- アクセスロール（階層: __R ⊂ __RW ⊂ __RWM）。__ 2つでファンクショナルロールと区別する
CREATE ROLE IF NOT EXISTS DATASOURCE__R;
CREATE ROLE IF NOT EXISTS DATASOURCE__RW;
CREATE ROLE IF NOT EXISTS DATASOURCE__RWM;
GRANT ROLE DATASOURCE__R  TO ROLE DATASOURCE__RW;
GRANT ROLE DATASOURCE__RW TO ROLE DATASOURCE__RWM;

-- ファンクショナルロール
CREATE ROLE IF NOT EXISTS DATASOURCE_USER;
CREATE ROLE IF NOT EXISTS DATASOURCE_DEVELOPER;
CREATE ROLE IF NOT EXISTS DATASOURCE_MANAGER;
CREATE ROLE IF NOT EXISTS DATASOURCE_ADMIN;

-- ファンクショナルロールへアクセスロールを付与
GRANT ROLE DATASOURCE__R   TO ROLE DATASOURCE_USER;
GRANT ROLE DATASOURCE__RW  TO ROLE DATASOURCE_DEVELOPER;
GRANT ROLE DATASOURCE__RWM TO ROLE DATASOURCE_MANAGER;

-- Adminに他のファンクショナルロールをぶら下げる（階層化）
GRANT ROLE DATASOURCE_USER      TO ROLE DATASOURCE_DEVELOPER;
GRANT ROLE DATASOURCE_DEVELOPER TO ROLE DATASOURCE_MANAGER;
GRANT ROLE DATASOURCE_MANAGER   TO ROLE DATASOURCE_ADMIN;

-- ---------------------------------------------------
-- SALES DB 用ロール
-- ---------------------------------------------------
CREATE ROLE IF NOT EXISTS SALES__R;
CREATE ROLE IF NOT EXISTS SALES__RW;
CREATE ROLE IF NOT EXISTS SALES__RWM;
GRANT ROLE SALES__R  TO ROLE SALES__RW;
GRANT ROLE SALES__RW TO ROLE SALES__RWM;

CREATE ROLE IF NOT EXISTS SALES_USER;
CREATE ROLE IF NOT EXISTS SALES_DEVELOPER;
CREATE ROLE IF NOT EXISTS SALES_MANAGER;
CREATE ROLE IF NOT EXISTS SALES_ADMIN;

GRANT ROLE SALES__R   TO ROLE SALES_USER;
GRANT ROLE SALES__RW  TO ROLE SALES_DEVELOPER;
GRANT ROLE SALES__RWM TO ROLE SALES_MANAGER;

GRANT ROLE SALES_USER      TO ROLE SALES_DEVELOPER;
GRANT ROLE SALES_DEVELOPER TO ROLE SALES_MANAGER;
GRANT ROLE SALES_MANAGER   TO ROLE SALES_ADMIN;

-- ---------------------------------------------------
-- WH用ロール（USEは全ファンクショナルロール、MANAGEはAdminのみ）
-- ---------------------------------------------------
-- SALES_WH: 分析・BI用
CREATE ROLE IF NOT EXISTS SALES_WH_USAGE;
CREATE ROLE IF NOT EXISTS SALES_WH_ADMIN;

GRANT ROLE SALES_WH_USAGE TO ROLE DATASOURCE_USER;
GRANT ROLE SALES_WH_USAGE TO ROLE DATASOURCE_DEVELOPER;
GRANT ROLE SALES_WH_USAGE TO ROLE DATASOURCE_MANAGER;
GRANT ROLE SALES_WH_USAGE TO ROLE DATASOURCE_ADMIN;
GRANT ROLE SALES_WH_USAGE TO ROLE SALES_USER;
GRANT ROLE SALES_WH_USAGE TO ROLE SALES_DEVELOPER;
GRANT ROLE SALES_WH_USAGE TO ROLE SALES_MANAGER;
GRANT ROLE SALES_WH_USAGE TO ROLE SALES_ADMIN;

GRANT ROLE SALES_WH_ADMIN TO ROLE DATASOURCE_ADMIN;
GRANT ROLE SALES_WH_ADMIN TO ROLE SALES_ADMIN;

-- DATASOURCE_WH: 取り込み用（S3 COPY等）。USAGEはDATASOURCE系ファンクショナルロールのみ
CREATE ROLE IF NOT EXISTS DATASOURCE_WH_USAGE;
CREATE ROLE IF NOT EXISTS DATASOURCE_WH_ADMIN;

GRANT ROLE DATASOURCE_WH_USAGE TO ROLE DATASOURCE_USER;
GRANT ROLE DATASOURCE_WH_USAGE TO ROLE DATASOURCE_DEVELOPER;
GRANT ROLE DATASOURCE_WH_USAGE TO ROLE DATASOURCE_MANAGER;
GRANT ROLE DATASOURCE_WH_USAGE TO ROLE DATASOURCE_ADMIN;

GRANT ROLE DATASOURCE_WH_ADMIN TO ROLE DATASOURCE_ADMIN;

-- ---------------------------------------------------
-- dbt実行専用ファンクショナルロール（SALES_TRANSFORMER）
-- 縦一本の user→developer→manager→Admin 階層には当てはまらない横串ロール。
--   - SALES__RWM     : silver/gold スキーマ・テーブル・ビューの作成 + 読み書き
--   - DATASOURCE__R  : raw(Salesforce)データの参照（SALES系ロールには未付与のため明示付与）
--   - SALES_WH_USAGE : SALES_WH の利用
-- 参照: ../構成.md #### Role（dbtはAnalyticsスキーマでbuildを実行）
-- ---------------------------------------------------
CREATE ROLE IF NOT EXISTS SALES_TRANSFORMER
  COMMENT = 'dbt(build/run/test)実行用。SALESの作成権限 + DATASOURCEの参照 + WH USAGE';

GRANT ROLE SALES__RWM     TO ROLE SALES_TRANSFORMER;
GRANT ROLE DATASOURCE__R  TO ROLE SALES_TRANSFORMER;
GRANT ROLE SALES_WH_USAGE TO ROLE SALES_TRANSFORMER;

-- 管理系ロールから見えるように内包
GRANT ROLE SALES_TRANSFORMER TO ROLE SALES_ADMIN;

-- SYSADMIN配下に集約（Snowflakeの一般的な運用パターン。方針次第で削除可）
GRANT ROLE DATASOURCE_ADMIN  TO ROLE SYSADMIN;
GRANT ROLE SALES_ADMIN       TO ROLE SYSADMIN;
GRANT ROLE SALES_TRANSFORMER TO ROLE SYSADMIN;

-- ---------------------------------------------------
-- ウェアハウス
-- ---------------------------------------------------
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS SALES_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'PoC用。サイズ・自動停止秒数は要調整';

CREATE WAREHOUSE IF NOT EXISTS DATASOURCE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'DATASOURCE取り込み用（S3 COPY等）。PoC用、サイズ・自動停止秒数は要調整';

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE SALES_WH TO ROLE SALES_WH_USAGE;
GRANT OPERATE, MODIFY ON WAREHOUSE SALES_WH TO ROLE SALES_WH_ADMIN;
GRANT USAGE ON WAREHOUSE DATASOURCE_WH TO ROLE DATASOURCE_WH_USAGE;
GRANT OPERATE, MODIFY ON WAREHOUSE DATASOURCE_WH TO ROLE DATASOURCE_WH_ADMIN;

-- ---------------------------------------------------
-- リソースモニター（CREDIT_QUOTAは仮値。要調整）
-- 通知先（Notification Integration）は構成.mdで未定のため未設定
-- ---------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS SALES_RM WITH
  CREDIT_QUOTA = 100
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE SALES_WH SET RESOURCE_MONITOR = SALES_RM;

CREATE RESOURCE MONITOR IF NOT EXISTS DATASOURCE_RM WITH
  CREDIT_QUOTA = 100
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE DATASOURCE_WH SET RESOURCE_MONITOR = DATASOURCE_RM;
