-- =====================================================
-- 03_grants.sql
-- アクセスロールへの権限付与（DB単位で一律付与、スキーマ別の細分化はしない）
-- Future Grants: GRANT ... ON FUTURE で新規オブジェクトにも自動付与
-- 参照: ../構成.md #### Role
--   Future Grants：GRANT ... ON FUTUREでスキーマ単位に自動付与
--   アクセス範囲：スキーマ単位では分けず、DB単位で一律付与
--
-- 実行ロール: SECURITYADMIN
--   Future Grantの定義にはアカウントレベルのMANAGE GRANTS権限が必要で、
--   DBオーナーシップだけでは不足する。SECURITYADMINは既定でMANAGE GRANTSを持ち、
--   非所有オブジェクトへのGRANTも可能なため、付与管理をここに一元化する。
-- =====================================================

-- ---------------------------------------------------
-- DATASOURCE（オーナーはDATASOURCE_ADMIN）
-- ---------------------------------------------------
USE ROLE SECURITYADMIN;

-- R: 参照
GRANT USAGE ON DATABASE DATASOURCE TO ROLE DATASOURCE__R;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE__R;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE__R;
GRANT SELECT ON ALL TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE__R;
GRANT SELECT ON FUTURE TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE__R;
GRANT SELECT ON ALL VIEWS IN DATABASE DATASOURCE TO ROLE DATASOURCE__R;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DATASOURCE TO ROLE DATASOURCE__R;

-- RW: 参照+更新（Rを継承済みのため追加分のみ）
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE__RW;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE__RW;

-- RWM: 参照+更新+作成/管理（RWを継承済みのため追加分のみ）
-- DBレベルに付与できる作成権限はCREATE SCHEMAのみ。
-- テーブル等の作成権限はスキーマレベル専用のため下のALL/FUTURE SCHEMASで付与する。
GRANT CREATE SCHEMA ON DATABASE DATASOURCE TO ROLE DATASOURCE__RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM
  ON ALL SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE__RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM
  ON FUTURE SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE__RWM;

-- ---------------------------------------------------
-- SALES（オーナーはSALES_ADMIN）
-- ---------------------------------------------------
-- 実行ロールはSECURITYADMINのまま（上記の理由と同じ）

-- R: 参照
GRANT USAGE ON DATABASE SALES TO ROLE SALES__R;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES TO ROLE SALES__R;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SALES TO ROLE SALES__R;
GRANT SELECT ON ALL TABLES IN DATABASE SALES TO ROLE SALES__R;
GRANT SELECT ON FUTURE TABLES IN DATABASE SALES TO ROLE SALES__R;
GRANT SELECT ON ALL VIEWS IN DATABASE SALES TO ROLE SALES__R;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SALES TO ROLE SALES__R;

-- RW: 参照+更新
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE SALES TO ROLE SALES__RW;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE SALES TO ROLE SALES__RW;

-- RWM: 参照+更新+作成/管理
-- DBレベルに付与できる作成権限はCREATE SCHEMAのみ。
-- テーブル等の作成権限はスキーマレベル専用のため下のALL/FUTURE SCHEMASで付与する。
-- CREATE AGENT / CREATE CORTEX SEARCH SERVICE は CoWork(旧Snowflake Intelligence)向け。
-- 詳細な付与は 08_cowork_agents.sql 側にもあるが、スキーマ作成権限としてここで一括付与する。
GRANT CREATE SCHEMA ON DATABASE SALES TO ROLE SALES__RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM, CREATE SEMANTIC VIEW,
      CREATE AGENT, CREATE CORTEX SEARCH SERVICE
  ON ALL SCHEMAS IN DATABASE SALES TO ROLE SALES__RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM, CREATE SEMANTIC VIEW,
      CREATE AGENT, CREATE CORTEX SEARCH SERVICE
  ON FUTURE SCHEMAS IN DATABASE SALES TO ROLE SALES__RWM;
