-- =====================================================
-- 03_grants.sql
-- アクセスロールへの権限付与（DB単位で一律付与、スキーマ別の細分化はしない）
-- Future Grants: GRANT ... ON FUTURE で新規オブジェクトにも自動付与
-- 参照: ../構成.md #### Role
--   Future Grants：GRANT ... ON FUTUREでスキーマ単位に自動付与
--   アクセス範囲：スキーマ単位では分けず、DB単位で一律付与
-- =====================================================

-- ---------------------------------------------------
-- DATASOURCE（オーナーはDATASOURCE_ADMIN）
-- ---------------------------------------------------
USE ROLE DATASOURCE_ADMIN;

-- R: 参照
GRANT USAGE ON DATABASE DATASOURCE TO ROLE DATASOURCE_R;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE_R;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE_R;
GRANT SELECT ON ALL TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE_R;
GRANT SELECT ON FUTURE TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE_R;
GRANT SELECT ON ALL VIEWS IN DATABASE DATASOURCE TO ROLE DATASOURCE_R;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DATASOURCE TO ROLE DATASOURCE_R;

-- RW: 参照+更新（Rを継承済みのため追加分のみ）
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE_RW;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE DATASOURCE TO ROLE DATASOURCE_RW;

-- RWM: 参照+更新+作成/管理（RWを継承済みのため追加分のみ）
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM, CREATE SCHEMA
  ON DATABASE DATASOURCE TO ROLE DATASOURCE_RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM
  ON ALL SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE_RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM
  ON FUTURE SCHEMAS IN DATABASE DATASOURCE TO ROLE DATASOURCE_RWM;

-- ---------------------------------------------------
-- SALES（オーナーはSALES_ADMIN）
-- ---------------------------------------------------
USE ROLE SALES_ADMIN;

-- R: 参照
GRANT USAGE ON DATABASE SALES TO ROLE SALES_R;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES TO ROLE SALES_R;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SALES TO ROLE SALES_R;
GRANT SELECT ON ALL TABLES IN DATABASE SALES TO ROLE SALES_R;
GRANT SELECT ON FUTURE TABLES IN DATABASE SALES TO ROLE SALES_R;
GRANT SELECT ON ALL VIEWS IN DATABASE SALES TO ROLE SALES_R;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SALES TO ROLE SALES_R;

-- RW: 参照+更新
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE SALES TO ROLE SALES_RW;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE SALES TO ROLE SALES_RW;

-- RWM: 参照+更新+作成/管理
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM, CREATE SCHEMA,
      CREATE SEMANTIC VIEW
  ON DATABASE SALES TO ROLE SALES_RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM, CREATE SEMANTIC VIEW
  ON ALL SCHEMAS IN DATABASE SALES TO ROLE SALES_RWM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE TASK, CREATE STREAM, CREATE SEMANTIC VIEW
  ON FUTURE SCHEMAS IN DATABASE SALES TO ROLE SALES_RWM;
